version: 1.0.{build}

install:
    - nuget restore
    
build:
  project: ExtSecureChat.Future.sln
  verbosity: detailed

environment:
    COVERALLS_REPO_TOKEN:  
       secure: Yy0q2rDut+F6ry3DBte63dMm1tmFAuu36vu2CcKOi2l5z5/j00MYuDvaZImk7dA9
 
after_test: 
# generate report for MSTest testing framework:
    -cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 17.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:ExtSecureChat.Future.Tests/bin/debug/ExtSecureChat.Future.Tests.dll" -output:coverage.xml
        
    - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%